In [1]:
print("hello MLP")

hello MLP


In [9]:
import numpy as np

In [6]:
a=np.array([1,2,3,4])  #print of array
print(a)

[1 2 3 4]


In [4]:
print("array :",a)
print(f"array a(a)")
print("array a:{}".format(a))   #format of array

array : [1 2 3 4]
array a(a)
array a:[1 2 3 4]


In [5]:
print(f"ndim:{a.ndim}")  #print min of array
print(f"size:{a.size}")  #print size of array
print(f"shape:{a.shape}") #print shape of aray
print(f"stype:{a.dtype}")  #print type of array
print(f"itemsize{a.itemsize}")  #number of element in array

ndim:1
size:4
shape:(4,)
stype:int32
itemsize4


In [6]:
b=np.array([[1,2,3],[4,5,6]]) #print arry
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
b=np.array([4,5,6,7])   #sum of array
c=np.add(a,b)
print(c)

[ 5  7  9 11]


In [8]:
b=np.array([4,5,6,7])   #multiuplication of array
c=np.multiply(a,b)
print(c)

[ 4 10 18 28]


In [9]:
b=np.array([4,5,6,7])  #division of array
c=np.divide(a,b)
print(c)

[0.25       0.4        0.5        0.57142857]


In [10]:
b=np.array([4,5,6,7])   #substarction of array
c=np.subtract(a,b)
print(c)

[-3 -3 -3 -3]


In [11]:
b=np.array([4,5,6,7])  #remainder of array
c=np.remainder(a,b)
print(c)

[1 2 3 4]


In [12]:
b=np.array([4,5,6,7])  #absolutre of array
c=np.absolute(a,b)
print(c)

[1 2 3 4]


In [13]:
b=np.array([4,5,6,7])  #print mod of array
c=np.mod(a,b)
print(c)

[1 2 3 4]


In [8]:
e=np.array(['hetu','viya'])  
print(e)

['hetu' 'viya']


In [16]:
e=np.size(['Riddhi','htasvi','Mansi']) #size of array
print(e)

3


In [17]:
z=np.zeros((2,3)) #print that array contain zero
print(z)

[[0. 0. 0.]
 [0. 0. 0.]]


In [21]:
one=np.ones((3,3))  
print(one)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [28]:
empty=np.empty((2,2))
print(empty)

[[0.25       0.4       ]
 [0.5        0.57142857]]


In [31]:
a=np.array([[2,3,5],[5,6,7]])  #sliced the array
print(a)
sliced_arr=a[1,2]
print(sliced_arr)

[[2 3 5]
 [5 6 7]]
7


In [37]:
indexed_arr=a[[1,0],[0,1]]  #indexd of array
print(indexed_arr,"indexed")

[5 3] indexed


In [38]:
print(a.sum())  #print the sum of element in the array

28


In [3]:
a1=np.array([25,45,50])   #print the squre root of element in the array
print(np.sqrt(a1))

[5.         6.70820393 7.07106781]


In [10]:
b=a+5   #add 5 in each elememt
print(b)

[6 7 8 9]


In [11]:
m1=np.array([[1,2,3],[4,5,6],[7,8,9]])    
m2=np.array([[7,2,9],[4,5,6],[7,8,9]])
m3=np.dot(m1,m2)     #dot use for matrix multiplication
print(m3)


[[ 36  36  48]
 [ 90  81 120]
 [144 126 192]]


In [17]:
bool=np.array([[True,True,False],[True,False,False]]) #for and operation use all
print("all() with axis none",np.all(bool))
print("all() with axis=0 ",np.all(bool,axis=0))  #zero means column
print("all() with axis=1 ",np.all(bool,axis=1))  #one means row

all() with axis none False
all() with axis=0  [ True False False]
all() with axis=1  [False False]


In [16]:
bool=np.array([[True,True,False],[True,False,False]])   #for or operation use any
print("any() with axis none",np.any(bool))
print("any() with axis=0 ",np.any(bool,axis=0))
print("any() with axis=1 ",np.any(bool,axis=1))

any() with axis none True
any() with axis=0  [ True  True False]
any() with axis=1  [ True  True]


In [19]:
a1=np.arange(8)  #print the araay and arange in sequence with given numbert
print(a1)
re=a1.reshape(2,4) #reshape the array
print(re)

[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]


In [20]:
print(m1)
print(m2)
print(m3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 2 9]
 [4 5 6]
 [7 8 9]]
[[ 36  36  48]
 [ 90  81 120]
 [144 126 192]]


In [23]:
h=np.hstack((m1,m2,m3))  #horizontal stack
print(h)

[[  1   2   3   7   2   9  36  36  48]
 [  4   5   6   4   5   6  90  81 120]
 [  7   8   9   7   8   9 144 126 192]]


In [25]:
hsplit=np.hsplit(h,3)  #horizontal split
print(hsplit)

[array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]), array([[7, 2, 9],
       [4, 5, 6],
       [7, 8, 9]]), array([[ 36,  36,  48],
       [ 90,  81, 120],
       [144, 126, 192]])]


In [27]:
vsplit=np.vsplit(h,3) #vertiacl split
print(vsplit)

[array([[ 1,  2,  3,  7,  2,  9, 36, 36, 48]]), array([[  4,   5,   6,   4,   5,   6,  90,  81, 120]]), array([[  7,   8,   9,   7,   8,   9, 144, 126, 192]])]


In [29]:
arr=np.array([23,45,67,89])
print("sqrt:",np.sqrt(arr))  #return the squre root of each element
print("exp:",np.exp(arr))    #return the exponentilas of each element
print("sin:",np.sin(arr))    #return the sin of each element
print("cos:",np.cos(arr))    #return the cosime of each element
print("log:",np.log(arr))    #return the logarithm of each element
print("sum:",np.sum(arr))    #return the sum total in the array
print("std:",np.std(arr))    #return the standard deviation in the array

sqrt: [4.79583152 6.70820393 8.18535277 9.43398113]
exp: [9.74480345e+09 3.49342711e+19 1.25236317e+29 4.48961282e+38]
sin: [-0.8462204   0.85090352 -0.85551998  0.86006941]
cos: [-0.53283302  0.52532199 -0.5177698   0.51017704]
log: [3.13549422 3.80666249 4.20469262 4.48863637]
sum: 224
std: 24.596747752497688


In [30]:
print("random:{}\n".format(np.random.random(20)));  #print the random value in array
print("rand:{}\n".format(np.random.rand(3,4)));
print("randint:{}\n".format(np.random.randint(0,100,20)));
print("permutatopn:{}\n".format(np.random.permutation(np.arange(20))));  #permutation use for combination





random:[0.76896584 0.90170074 0.42411175 0.13468571 0.07694748 0.43866619
 0.87350778 0.23925304 0.82662212 0.91828002 0.92152619 0.33371929
 0.4513621  0.73343297 0.26858001 0.69542723 0.34282616 0.20915089
 0.95580845 0.25104822]

rand:[[0.31128859 0.55472339 0.62994144 0.55976372]
 [0.549807   0.9314941  0.92262821 0.23421488]
 [0.4194875  0.92515654 0.83417849 0.16039725]]

randint:[43 66 99 52  2  1 38 68  5 37 46 34 19 59  0 98 49 89 80 92]

permutatopn:[17  2  7 13  3  6 10 18 16 12  9 14  1  8 15  5 19  4 11  0]

